esphome:
  name: esp32-led-controller

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:
api:
ota:
  - platform: esphome
    password: "e8e2543495082c2bcad2c089544e8d5c"
# ---------- Ethernet ----------
ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 1

# ---------- Smart LED strip on GPIO15 (e.g. WS2812B) ----------
light:
  - platform: esp32_rmt_led_strip
    name: "Smart LED Strip"
    pin: GPIO15
    num_leds: 5
    rgb_order: GRB
    chipset: ws2812

  - platform: rgb
    name: "RGB Strip"
    red: rgb_red
    green: rgb_green
    blue: rgb_blue

output:
  - platform: ledc
    pin: GPIO4
    id: rgb_red
    inverted: True

  - platform: ledc
    pin: GPIO12
    id: rgb_green
    inverted: True

  - platform: ledc
    pin: GPIO14
    id: rgb_blue
    inverted: True

# ---------- IR receiver TSOP38238 on GPIO34 ----------
remote_receiver:
  pin:
    number: GPIO34
    inverted: true        # TSOP38238 output is active LOW
  dump: all               # log all received codes in ESPHome logs
  filter: 50us
  idle: 4ms
  tolerance: 55%

# Example: map a specific IR code to an action (optional, once you know the code)
# binary_sensor:
#   - platform: remote_receiver
#     name: "IR Power Button"
#     nec:
#       address: 0x00FF
#       command: 0xA25D
#     on_press:
#       - light.toggle: smart_led_strip   # or use the entity_id from HA
